default_prefix: '!'
debug: false

description: Я — бот, написанный специально для вики-серверов. Моя задача — облегчить рутинные процедуры, вроде верификации или вывода правок. Но кроме этого я включаю в себя игры, так что если захотите развлечься — не стесняйтесь!
primary_color: 0x5d77bf

credentials:
  token: token

test_guilds:
 - 538628976067870720 # Bananas
 - 509431359761285120 # Official server
 - 560468092866527244 # Dark Castle

cogs:
  - jishaku
#  - cogs.help
  - cogs.info
  - cogs.fandom
  - cogs.verification
  - cogs.wikilinks

emojis:
  success: "<:success:1001451792623730758>"
  error: "<:error:1001451516969877504>"